@hostname = http://localhost:8000

###Get all notes
get {{hostname}}/notes

### Get notes by username. Input info is param @getname
@getname = FirstUser
get {{hostname}}/notes/user/{{getname}}

### Get one note by id. Input info is param @getid
@getid = 62289b5845ad7dd7f5a98cdb
get {{hostname}}/notes/{{getid}}

### Create one note. Input info is json with string 'text', string 'userName', numbers 'top' and 'left'
post {{hostname}}/notes
Content-Type: application/json

{
    "text": "First text",
    "userName": "FirstUser",
    "top": 100,
    "left": 200
}

### Update one note. Update info is json with string 'username', string 'text', numbers 'top' and 'left'
put {{hostname}}/notes
Content-Type: application/json

{
    "id": "622884bfef1ee7f727b0838b",
    "text": "Third text",
    "top": 200,
    "left": 100
}

### Delete one note. Input info is param @deleteid
@deleteid = 62289b5e45ad7dd7f5a98cdf
delete {{hostname}}/notes/{{deleteid}}