@hostname = http://localhost:8000

###Get all users
get {{hostname}}/users

### Get one user by name. Input info is param @getname
@getname = FirstUser
get {{hostname}}/users/{{getname}}

### Create one user. Input info is json with only one string 'name'. Type must be string and not empty
post {{hostname}}/users
Content-Type: application/json

{
    "name": "ThirdUser"
}

### Update one user. Update info is json with string 'name' and string 'newName'
put {{hostname}}/users
Content-Type: application/json

{
    "name": "FirstUser",
    "newName": "StillFirstUser"
}

### Delete one user. Input info is param @getname
@deletename = StillFirstUser
delete {{hostname}}/users/{{deletename}}