# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: note_board_mongodb
    env_file: .env
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
